### ISSUE TITLE
CLI argument to work without config files

### ISSUE THREAD

**Issue by Lysholm** [bcicen/slackcat#62]
Hi i want to use this in a CI/CD runner to output status/changelog to slack. It would be nice to not have to set up and copy config files into the containers but instead specify the token slackcat should use; `--token` would be perfect.

**Comment by bcicen** [comment]
added in https://github.com/bcicen/slackcat/commit/1783046c2a99637f18178ab1ca1912f286746bd5, to be included in the next release

**Comment by Lysholm** [comment]
Great stuff, looking forward to it. Using a ugly combination of `sed` and `curl` now. ;)
