### ISSUE TITLE
[Feature Request] Send comment only with no file

### ISSUE THREAD

**Issue by TrevorSayre** [bcicen/slackcat#63]
would like to be able to just:
`slackcat -c channelname --comment "test message"`

fire and forget

**Comment by TrevorSayre** [comment]
This may be solved with just:
`echo -e "test message" | slackcat -t -s -channel channelname`

**Comment by bcicen** [comment]
you should not need to `ctrl-c` when streaming; `slackcat` will exit when piped input reaches EOF. Using your example:

```# echo -e "test message" | slackcat -t -s -c team:channelname
slackcat connected to team as user
slackcat starting stream
test message
slackcat flushing remaining messages to Slack...
slackcat posted 1 message lines to channelname
```

**Comment by bcicen** [comment]
closing for now; feel free to reopen if you have further questions
