### ISSUE TITLE
Legacy tokens going away  May 5th, 2020?

### ISSUE THREAD

**Issue by bedge** [bcicen/slackcat#69]
https://api.slack.com/legacy/custom-integrations/legacy-tokens says:

"This tool will not allow creation of new tokens on May 5th, 2020. Learn more about why you shouldn't use it anymore."

Does slackcat support this?

**Comment by bcicen** [comment]
While legacy tokens will longer be of use, OAuth tokens support and generation is already available via `slackcat --configure`
