### ISSUE TITLE
Legacy Slack API

### ISSUE THREAD

**Issue by n0madic** [bcicen/slackcat#71]
The package `github.com/bluele/slack` uses a legacy Slack API, for example, calling the `channels.list` method returns a warning:

> [WARN] This method is deprecated and is scheduled to cease functioning on 2021-02-24. Please use conversations.list or users.conversations instead. Learn more: https://api.slack.com/changelog/2020-01-deprecating-antecedents-to-the-conversations-api.

Slack App tokens don't work at all with this method...

I think it's time to move to modern libraries, for example `github.com/slack-go/slack`, before the utility stops working...

**Comment by nikolay** [comment]
@bcicen It stopped working today.

**Comment by frankcrawford** [comment]
So, does this mean it is totally dead?  Or is there a plan to fix it?

**Comment by nikolay** [comment]
@frankcrawford Yes, it looks dead to me. I started to work on a simple CLI wrapper of https://github.com/slack-go/slack.

**Comment by n0madic** [comment]
Made a pull request #75 with a working lib

**Comment by bcicen** [comment]
fix now published in [v1.7 release](https://github.com/bcicen/slackcat/releases/tag/1.7)
