### ISSUE TITLE
Download Link in README does not work

### ISSUE THREAD

**Issue by zdavatz** [bcicen/slackcat#79]
This does not work: 
```
curl -Lo slackcat https://github.com/bcicen/slackcat/releases/download/v1.7.1/slackcat-1.7.1-$(uname -s)-amd64
```
downloaded file is empty and says "not found" in the file.

**Comment by bcicen** [comment]
fixed in https://github.com/bcicen/slackcat/commit/1f57ebbd5a0fbf025fe79db7f398394f11f5c368; thanks for reporting
