### ISSUE TITLE
Says file uploaded, no file shows up in slack

### ISSUE THREAD

**Issue by mtfurlan** [bcicen/slackcat#80]
I'm running v1.7.1 on debian buster, the precompiled binary from the releases.
```
$ echo -e "hi\nthere" | slackcat --channel Slackbot --filename hello                                    
slackcat connected to $team as mark
slackcat file hello uploaded to Slackbot (0.228s)

$ slackcat -c $person /tmp/testFile 
slackcat connected to $team as mark
slackcat file testFile uploaded to $person (0.185s)
```
The files are not showing up in slack.
I've moved my config file and re-run `slackcat --configure` and re-authorized the thing, but no change.

`slackcat --list` works, so I'm pretty sure the token works.

What should I look into next to debug this?

**Comment by mtfurlan** [comment]
I just found all my test files in a PM with a bot.
The channel does not change based on what the default channel is set to in the config, or if I specify a channel with `--channel`.
It also doesn't warn me if I send files to a channel that doesn't exist.

**Comment by dougharris** [comment]
This is the same problem as in #82. I've submitted a patch for that.

**Comment by mtfurlan** [comment]
Closing this issue in favour of #82 then.
