### ISSUE TITLE
Upgrade the version in Homebrew

### ISSUE THREAD

**Issue by nikolay** [bcicen/slackcat#81]
It is still having the defunct versions 1.6 in there.

**Comment by dougharris** [comment]
PR submitted to homebrew: https://github.com/Homebrew/homebrew-core/pull/73777

I did this using the "[How To Open a Homebrew Pull Request](https://docs.brew.sh/How-To-Open-a-Homebrew-Pull-Request)" steps, specifically:

```bash
brew bump-formula-pr --sha256 5367e1ad32c6f895a3b85b9cb8a61aa73f402f86156db074e06f5f0a39614d19 --url https://github.com/bcicen/slackcat/archive/refs/tags/1.7.1.tar.gz slackcat
```

I got the URL from this repo's release page and then ran `sha512sum` on that to get the hash.

**Comment by dougharris** [comment]
and somebody else submitted the PR for 1.7.2 and it's available!

`brew update && brew upgrade slackcat`

**Comment by bcicen** [comment]
closing resolved

**Comment by nikolay** [comment]
Thank you! 🎉
