### ISSUE TITLE
DM doesn't go to correct user

### ISSUE THREAD

**Issue by truthdoug** [bcicen/slackcat#82]
**Summary:** When I tried to send a direct message, it went to the wrong user.

I try this to send a direct message to myself:

```bash
$ echo "Attempting remote message sent to Doug Harris (from Doug Harris)" | ./slackcat -s --channel dharris
slackcat connected to My Slack as dharris
slackcat starting stream
slackcat flushing remaining messages to Slack...
slackcat flushing remaining messages to Slack...
slackcat posted 1 message lines to dharris
```

Not only do I not get the message, but when I look at all DMs, I see that **it went to another user**. For the purposes of this ticket let's call this user `jdoe`.

If I do:

```bash
./slackcat --list
```

I see `jdoe` as the first in the list `im` users. Something like this:

```
# all channels and a bunch of groups and then...

[MySlack] [group]  mpdm-user1--dharris--usera--user3--user4-1
[MySlack] [group]  mpdm-user1--dharris--usera--user3-1
[MySlack] [group]  mpdm-user1--userb--userc--dharris-1
[MySlack] [group]  mpdm-user5--dharris--user1--user6-1
[MySlack] [im]  jdoe
[MySlack] [im]  anotheruser
[MySlack] [im]  onemoreuser

# and continuing the list of other users
```

I also tried this sending to a different user, *i.e.* not me and not `jdoe`. I got the same result: the message went to `jdoe`.

Using slackcat 1.7.1 on MacOS Catalina (downloaded from github).

**Comment by bcicen** [comment]
fix included in [1.7.2](https://github.com/bcicen/slackcat/releases/tag/1.7.2) release

**Comment by dougharris** [comment]
I'm using 1.7.2 from homebrew now and it's 💯

**Comment by bcicen** [comment]
closing resolved
