### ISSUE TITLE
[Feature] - Add the ability for a stream to send to a thread.

### ISSUE THREAD

**Issue by ArcticSnowman** [bcicen/slackcat#84]
Is would be useful to be able to send long streams of output to a threaded message.

The first message (or leading comment) goes to the selected channel and then all subsequent messages are threaded to the original.

**Comment by ArcticSnowman** [comment]
#85 PR created

**Comment by bcicen** [comment]
merged for inclusion in 1.7.3 release

**Comment by bcdady** [comment]
Is 1.7.3 released?
I just installed via homebrew, and I have version 1.7.2. I tried the `--thread` parameter based on the README, but got this error message:

```shell
Incorrect Usage. flag provided but not defined: -thread
```

**Comment by bcicen** [comment]
@bcdady 1.7.3 release published now
